In [1]:
import numpy as np 

In [4]:
data = np.zeros((10,10))
data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
# data[rows , cols]
data[1 : -1 , 1 : -1  ] = 1

In [9]:
data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
data2 = np.zeros((10,10))
data2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
data2[0] = data2[-1] = data2[: , 0] = data2[: , -1] = 1

In [22]:
data2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
type(data)

numpy.ndarray

In [26]:
matrix = np.array([[1,2,3] , [2,3,4] , [3,4,5]])
matrix

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [27]:
np.tril(matrix)

array([[1, 0, 0],
       [2, 3, 0],
       [3, 4, 5]])

In [28]:
np.triu(matrix)

array([[1, 2, 3],
       [0, 3, 4],
       [0, 0, 5]])

In [29]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.diag([1,3,1,3,4,5,6])

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 6]])

In [34]:
data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
np.diag(np.diag(data))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [46]:
np.random.seed(123)
mat1 = np.random.randint(1,4 , (3,3))
mat2 = np.random.randint(1,5 , (3,3))

In [47]:
mat1

array([[3, 2, 3],
       [3, 1, 3],
       [3, 2, 3]])

In [48]:
mat2

array([[4, 2, 3],
       [2, 1, 2],
       [3, 4, 2]])

In [49]:
mat1 * mat2

array([[12,  4,  9],
       [ 6,  1,  6],
       [ 9,  8,  6]])

In [50]:
mat1 + mat2

array([[7, 4, 6],
       [5, 2, 5],
       [6, 6, 5]])

In [60]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([1,3,3,5,5,7])
np.equal(arr1,arr2)

array([ True, False,  True, False,  True, False])

In [56]:
np.equal(arr1,arr2)

array([ True, False,  True, False,  True, False])

In [58]:
arr1[arr1 >= 4]

array([4, 5, 6])

In [59]:
arr1 >= 4

array([False, False, False,  True,  True,  True])

In [61]:
help(np.equal)

Help on ufunc:

equal = <ufunc 'equal'>
    equal(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Return (x1 == x2) element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        Input arrays.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [69]:
np.random.random((5,5))

array([[0.69340324, 0.51176338, 0.46426806, 0.56843069, 0.30254945],
       [0.49730879, 0.68326291, 0.91669867, 0.10892895, 0.49549179],
       [0.23283593, 0.43686066, 0.75154299, 0.48089213, 0.79772841],
       [0.28270293, 0.43341824, 0.00975735, 0.34079598, 0.68927201],
       [0.86936929, 0.26780382, 0.45674792, 0.26828131, 0.8370528 ]])

In [72]:
np.random.rand(5)

array([0.76383669, 0.1085423 , 0.51165472, 0.9097694 , 0.21837601])

In [71]:
np.random.randn(10)

array([-1.74042135, -0.5345051 , -0.93774867, -1.48630088, -0.02936315,
       -1.23714237,  0.07598604, -1.94519772, -0.23484041, -1.81456729])

In [85]:
arr1 = np.array([1.5,2,3,4,4,6])
arr2 = np.array([1,3,3,5,5,7])

In [87]:
np.isclose(arr1,arr2  , atol=.5)     #-.5 .... .5 

array([ True, False,  True, False, False, False])

In [89]:
mat1

array([[3, 2, 3],
       [3, 1, 3],
       [3, 2, 3]])

In [91]:
sum(np.diag(mat1))

7

In [92]:
np.trace(mat1) # sum of main diag

7

In [97]:
x = np.array([[1,2,3] , [2,3,5] , [1,6,8]])
x

array([[1, 2, 3],
       [2, 3, 5],
       [1, 6, 8]])

In [98]:
np.linalg.matrix_rank(x)

3

In [99]:
y = np.array([[1,2,3] , [2,3,5] , [1,6,7]])
y

array([[1, 2, 3],
       [2, 3, 5],
       [1, 6, 7]])

In [102]:
3 - 1 

2

In [101]:
np.linalg.matrix_rank(y)

2

In [104]:
# dir(np.linalg)

In [105]:
d = np.array([[1,2] , [3,4]])
d

array([[1, 2],
       [3, 4]])

In [107]:
np.ceil(np.linalg.det(d))

-2.0

In [109]:
int(np.linalg.det(d))

-2

In [110]:
mat1

array([[3, 2, 3],
       [3, 1, 3],
       [3, 2, 3]])

In [112]:
3*( (1* 3 ) - (2 * 3 ))     -2*((3 * 3 ) - (3 * 3 ))        +3*((3 * 2 ) - (3 * 1 ))

0

In [120]:
np.floor(2.8)

2.0

In [121]:
np.linalg.det(mat1)

0.0

In [124]:
mat1

array([[3, 2, 3],
       [3, 1, 3],
       [3, 2, 3]])

In [125]:
mat1.T

array([[3, 3, 3],
       [2, 1, 2],
       [3, 3, 3]])

In [128]:
m = np.array([[1,2],[2,3]])
m

array([[1, 2],
       [2, 3]])

In [130]:
de = -1
m_ = np.array([[3 , -2] , [-2 , 1]])
m_

array([[ 3, -2],
       [-2,  1]])

In [131]:
-1 * m_

array([[-3,  2],
       [ 2, -1]])

In [132]:
m.dot(m_)

array([[-1,  0],
       [ 0, -1]])

In [133]:
np.linalg.inv(m)

array([[-3.,  2.],
       [ 2., -1.]])

In [135]:
mat2

array([[4, 2, 3],
       [2, 1, 2],
       [3, 4, 2]])

In [137]:
mat2_ = np.linalg.inv(mat2)

In [138]:
mat2_

array([[ 1.2, -1.6, -0.2],
       [-0.4,  0.2,  0.4],
       [-1. ,  2. ,  0. ]])

In [140]:
mat2.dot(mat2_).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [141]:
mat1

array([[3, 2, 3],
       [3, 1, 3],
       [3, 2, 3]])

In [142]:
mat2

array([[4, 2, 3],
       [2, 1, 2],
       [3, 4, 2]])

In [143]:
3 * 4 + 2 * 2 + 3 * 3 

25

In [145]:
mat1.dot(mat2)

array([[25, 20, 19],
       [23, 19, 17],
       [25, 20, 19]])

In [144]:
# [a  b  c ]
# [d  e  f ]
# [0  1  2 ]
# (2,3) * (3 , 2)
# (2,2)

In [ ]:
# T
# det 
# inv
# rank
# trace
def matrix_operation(matrix):
    t     = matrix.T
    det   = np.linalg.det
    inv   = np.linalg.inv
    rank  = np.linalg.matrix_rank
    trace = np.trace
    return t , det , inv , rank , trace

In [ ]:
t , det , inv , rank , trace = matrix_operation(Matrix)

In [155]:
8/12

0.6666666666666666

In [157]:
1 - 4/12

0.6666666666666667

In [158]:
# sp = 1 - none zero / total 

In [159]:
mat2.size

9

In [160]:
mat2.shape

(3, 3)

In [171]:
data = np.array([[0,1,1,1,0,0,0,0,0,2] , [0,0,0,1,0,0,0,0,0,2] , [1,0,0,1,0,0,0,0,0,2]])
data

array([[0, 1, 1, 1, 0, 0, 0, 0, 0, 2],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 2],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 2]])

In [163]:
data.size

30

In [166]:
nonzero = np.count_nonzero(data)

In [168]:
1- (nonzero/data.size)

0.7

In [169]:
from scipy.sparse import csr_matrix , csc_matrix

In [170]:
print(csr_matrix(data))

  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 9)	2
  (1, 3)	1
  (1, 9)	2
  (2, 0)	1
  (2, 3)	1
  (2, 9)	2


In [172]:
print(csc_matrix(data))

  (2, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (1, 3)	1
  (2, 3)	1
  (0, 9)	2
  (1, 9)	2
  (2, 9)	2


In [173]:
# data ?
# how to measure data?
# mean 
# median 
# mode

# variance 
# std

# covraiance 
# correlation 

# quartilies
# outliers 

# probability

In [ ]:
# pandas    
# matplotlib.pyplot 
# seaborn 
# plotly 